### ISSUE TITLE
hgemmBatch broken

### ISSUE THREAD

**Issue by nouiz** [Theano/libgpuarray#543]
```
$ theano-nose theano/gpuarray/tests/test_blas.py -s --pdb --pdb-failure
Using cuDNN version 7002 on context None
Mapped name None to device cuda: GeForce GTX 750 (0000:05:00.0)
.Disabling C code for BatchedDot due to unsupported float16
> /u/bastienf/repos/Theano/theano/compile/function_module.py(903)__call__()
-> self.fn() if output_subset is None else\
(Pdb) l
912  	                if hasattr(self.fn, 'thunks'):
913  	                    thunk = self.fn.thunks[self.fn.position_of_error]
914  	                gof.link.raise_with_op(
915  	                    node=self.fn.nodes[self.fn.position_of_error],
916  	                    thunk=thunk,
917  ->	                    storage_map=getattr(self.fn, 'storage_map', None))
918  	            else:
919  	                # old-style linkers raise their own exceptions
920  	                raise
921  	
922  	        dt_fn = time.time() - t0_fn
(Pdb) s
E...........................................SSS................SSS...........
======================================================================
ERROR: test_all (theano.gpuarray.tests.test_blas.GpuGemmBatchTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/u/bastienf/repos/Theano/theano/gpuarray/tests/test_basic_ops.py", line 97, in test_all
    self.run_case(testname, inputs)
  File "/u/bastienf/repos/Theano/theano/gpuarray/tests/test_basic_ops.py", line 131, in run_case
    variables = f_tst()
  File "/u/bastienf/repos/Theano/theano/compile/function_module.py", line 917, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/u/bastienf/repos/Theano/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/u/bastienf/repos/Theano/theano/compile/function_module.py", line 903, in __call__
    self.fn() if output_subset is None else\
RuntimeError: ('Blas operation not supported by library in use: hgemmBatch\nApply node that caused the error: GpuGemmBatch{inplace=True}(GpuAllocEmpty{dtype=\'float16\', context_name=None}.0, TensorConstant{1.0}, GpuFromHost<None>.0, GpuFromHost<None>.0, TensorConstant{0.0})\nToposort index: 11\nInputs types: [GpuArrayType<None>(float16, 3D), TensorType(float32, scalar), GpuArrayType<None>(float16, 3D), GpuArrayType<None>(float16, 3D), TensorType(float32, scalar)]\nInputs shapes: [(3, 4, 7), (), (3, 4, 4), (3, 4, 7), ()]\nInputs strides: [(56, 14, 2), (), (32, 8, 2), (56, 14, 2), ()]\nInputs values: [\'not shown\', array(1.0, dtype=float32), \'not shown\', \'not shown\', array(0.0, dtype=float32)]\nOutputs clients: [[GpuElemwise{Composite{((i0 * i1) + (i2 * i3))}}[(0, 1)]<gpuarray>(InplaceGpuDimShuffle{x,x,x}.0, GpuGemmBatch{inplace=True}.0, InplaceGpuDimShuffle{x,x,x}.0, GpuFromHost<None>.0)]]\n\nBacktrace when the node is created(use Theano flag traceback.limit=N to make it longer):\n  File "/u/bastienf/repos/Theano/theano/gpuarray/tests/test_basic_ops.py", line 97, in test_all\n    self.run_case(testname, inputs)\n  File "/u/bastienf/repos/Theano/theano/gpuarray/tests/test_basic_ops.py", line 115, in run_case\n    f_tst = inplace_func([], node_tst.outputs, mode=mode_gpu)\n  File "/u/bastienf/repos/Theano/theano/gpuarray/tests/test_basic_ops.py", line 42, in inplace_func\n    on_unused_input=on_unused_input, name=name)\n  File "/u/bastienf/repos/Theano/theano/compile/function.py", line 317, in function\n    output_keys=output_keys)\n  File "/u/bastienf/repos/Theano/theano/compile/pfunc.py", line 486, in pfunc\n    output_keys=output_keys)\n  File "/u/bastienf/repos/Theano/theano/compile/function_module.py", line 1839, in orig_function\n    name=name)\n  File "/u/bastienf/repos/Theano/theano/compile/function_module.py", line 1519, in __init__\n    optimizer_profile = optimizer(fgraph)\n  File "/u/bastienf/repos/Theano/theano/gof/opt.py", line 99, in __call__\n    return self.optimize(fgraph)\n  File "/u/bastienf/repos/Theano/theano/gof/opt.py", line 88, in optimize\n    ret = self.apply(fgraph, *args, **kwargs)\n  File "/u/bastienf/repos/Theano/theano/gof/opt.py", line 242, in apply\n    sub_prof = optimizer.optimize(fgraph)\n  File "/u/bastienf/repos/Theano/theano/gof/opt.py", line 88, in optimize\n    ret = self.apply(fgraph, *args, **kwargs)\n  File "/u/bastienf/repos/Theano/theano/gof/opt.py", line 2128, in apply\n    nb += self.process_node(fgraph, node)\n  File "/u/bastienf/repos/Theano/theano/gof/opt.py", line 2019, in process_node\n    replacements = lopt.transform(node)\n  File "/u/bastienf/repos/Theano/theano/gof/opt.py", line 1366, in transform\n    new_repl = opt.transform(node)\n  File "/u/bastienf/repos/Theano/theano/gpuarray/opt_util.py", line 333, in opt\n    return maker(node, inputs)\n  File "/u/bastienf/repos/Theano/theano/gpuarray/blas.py", line 1871, in local_inplace_gpuagemmbatch\n    return [gpugemmbatch_inplace(*inputs)]\n  File "/u/bastienf/repos/Theano/theano/gof/op.py", line 615, in __call__\n    node = self.make_node(*inputs, **kwargs)\n  File "/u/bastienf/repos/Theano/theano/gpuarray/blas.py", line 394, in make_node\n    return Apply(self, [C, alpha, A, B, beta], [C.type()])\n  File "/u/bastienf/repos/Theano/theano/gof/type.py", line 419, in __call__\n    return utils.add_tag_trace(self.make_variable(name))\n  File "/u/bastienf/repos/Theano/theano/gof/utils.py", line 108, in add_tag_trace\n    tr = simple_extract_stack(limit=user_line, skips=skips)\n  File "/Tmp/lisa/os_v5/anaconda/lib/python2.7/unittest/case.py", line 329, in run\n    testMethod()\n  File "/u/bastienf/repos/Theano/theano/gpuarray/tests/test_basic_ops.py", line 97, in test_all\n    self.run_case(testname, inputs)\n  File "/u/bastienf/repos/Theano/theano/gpuarray/tests/test_basic_ops.py", line 115, in run_case\n    f_tst = inplace_func([], node_tst.outputs, mode=mode_gpu)\n  File "/u/bastienf/repos/Theano/theano/gpuarray/tests/test_basic_ops.py", line 42, in inplace_func\n    on_unused_input=on_unused_input, name=name)\n  File "/u/bastienf/repos/Theano/theano/compile/function.py", line 317, in function\n    output_keys=output_keys)\n  File "/u/bastienf/repos/Theano/theano/compile/pfunc.py", line 486, in pfunc\n    output_keys=output_keys)\n  File "/u/bastienf/repos/Theano/theano/compile/function_module.py", line 1839, in orig_function\n    name=name)\n  File "/u/bastienf/repos/Theano/theano/compile/function_module.py", line 1519, in __init__\n    optimizer_profile = optimizer(fgraph)\n  File "/u/bastienf/repos/Theano/theano/gof/opt.py", line 99, in __call__\n    return self.optimize(fgraph)\n  File "/u/bastienf/repos/Theano/theano/gof/opt.py", line 88, in optimize\n    ret = self.apply(fgraph, *args, **kwargs)\n  File "/u/bastienf/repos/Theano/theano/gof/opt.py", line 242, in apply\n    sub_prof = optimizer.optimize(fgraph)\n  File "/u/bastienf/repos/Theano/theano/gof/opt.py", line 88, in optimize\n    ret = self.apply(fgraph, *args, **kwargs)\n  File "/u/bastienf/repos/Theano/theano/gof/opt.py", line 242, in apply\n    sub_prof = optimizer.optimize(fgraph)\n  File "/u/bastienf/repos/Theano/theano/gof/opt.py", line 88, in optimize\n    ret = self.apply(fgraph, *args, **kwargs)\n  File "/u/bastienf/repos/Theano/theano/gpuarray/opt.py", line 417, in apply\n    node.outputs)\n  File "/u/bastienf/repos/Theano/theano/gpuarray/opt.py", line 1349, in local_gpua_gemmbatch\n    a, b, np.asarray(0.0, dtype=out_dtype))\n  File "/u/bastienf/repos/Theano/theano/gof/op.py", line 615, in __call__\n    node = self.make_node(*inputs, **kwargs)\n  File "/u/bastienf/repos/Theano/theano/gpuarray/blas.py", line 394, in make_node\n    return Apply(self, [C, alpha, A, B, beta], [C.type()])\n  File "/u/bastienf/repos/Theano/theano/gof/type.py", line 419, in __call__\n    return utils.add_tag_trace(self.make_variable(name))\n  File "/u/bastienf/repos/Theano/theano/gof/utils.py", line 108, in add_tag_trace\n    tr = simple_extract_stack(limit=user_line, skips=skips)\n  File "/u/bastienf/repos/Theano/theano/gpuarray/tests/test_basic_ops.py", line 105, in run_case\n    node_tst = safe_make_node(self.op, *inputs_tst)\n  File "/u/bastienf/repos/Theano/theano/tensor/tests/test_basic.py", line 203, in safe_make_node\n    node = op(*inputs)\n  File "/u/bastienf/repos/Theano/theano/gpuarray/tests/test_blas.py", line 153, in <lambda>\n    op=lambda z, alpha, x, y, beta: alpha * batched_dot(x, y) + beta * z,\n  File "/u/bastienf/repos/Theano/theano/gof/op.py", line 615, in __call__\n    node = self.make_node(*inputs, **kwargs)\n  File "/u/bastienf/repos/Theano/theano/tensor/blas.py", line 2036, in make_node\n    return Apply(self, upcasted_inputs, [T.tensor(dtype, broadcastable)])\n  File "/u/bastienf/repos/Theano/theano/tensor/basic.py", line 641, in tensor\n    return TensorType(*args, **kwargs)(name=name)\n  File "/u/bastienf/repos/Theano/theano/gof/type.py", line 419, in __call__\n    return utils.add_tag_trace(self.make_variable(name))\n  File "/u/bastienf/repos/Theano/theano/gof/utils.py", line 108, in add_tag_trace\n    tr = simple_extract_stack(limit=user_line, skips=skips)\n  File "/u/bastienf/repos/Theano/theano/gpuarray/tests/test_basic_ops.py", line 105, in run_case\n    node_tst = safe_make_node(self.op, *inputs_tst)\n  File "/u/bastienf/repos/Theano/theano/tensor/tests/test_basic.py", line 203, in safe_make_node\n    node = op(*inputs)\n  File "/u/bastienf/repos/Theano/theano/gpuarray/tests/test_blas.py", line 153, in <lambda>\n    op=lambda z, alpha, x, y, beta: alpha * batched_dot(x, y) + beta * z,\n  File "/u/bastienf/repos/Theano/theano/gof/op.py", line 615, in __call__\n    node = self.make_node(*inputs, **kwargs)\n  File "/u/bastienf/repos/Theano/theano/tensor/blas.py", line 2036, in make_node\n    return Apply(self, upcasted_inputs, [T.tensor(dtype, broadcastable)])\n  File "/u/bastienf/repos/Theano/theano/tensor/basic.py", line 641, in tensor\n    return TensorType(*args, **kwargs)(name=name)\n  File "/u/bastienf/repos/Theano/theano/gof/type.py", line 419, in __call__\n    return utils.add_tag_trace(self.make_variable(name))\n  File "/u/bastienf/repos/Theano/theano/gof/utils.py", line 108, in add_tag_trace\n    tr = simple_extract_stack(limit=user_line, skips=skips)\n\nHINT: Use the Theano flag \'exception_verbosity=high\' for a debugprint and storage map footprint of this apply node.', 'Test GpuGemmBatch{inplace=True}::float16: exception when calling the Function')

----------------------------------------------------------------------
Ran 78 tests in 71.386s

FAILED (SKIP=6, errors=1)
```

It is strange. It pass on jenkins, but fail when run locally.

First reported [here](https://github.com/Theano/libgpuarray/pull/538#issuecomment-333838542), but moved to its own issue.

**Comment by abergeron** [comment]
The problem is due to the 384.xx driver.  It makes the blas call fail.  Not much we can do but report the issue.

**Comment by nouiz** [comment]
fixed.

**Comment by sclarkson** [comment]
I'm still seeing this error when running theano tests.

cublasHgemmBatched is available in CUDA 9.0+, but is presently unsupported by libgpuarray
https://github.com/Theano/libgpuarray/blob/04c289257c052b541f7478cd6193f6bc96124526/src/gpuarray_blas_cuda_cublas.c#L1852
